### ISSUE TITLE
SyntaxError: Unexpected token ]message: "Unexpected token ]"

### ISSUE THREAD

**Issue by EvgenPastushek** [OXTraining/MikhailLarchanka#20]
добрый вечер! есть вопрос. вот  часть ajax-запроса:

xhr.onreadystatechange = function(){
	if(xhr.readyState === 4){
		if(xhr.status === 200){
			newsBlock.innerHTML = "Загрузка..."; // удаление содержимого новостей
			var json = xhr.responseText; // до сюда все работает хорошо
			var jsinObj = JSON.parse(json); // с этой строки начинается ошибка
			newsBlock.innerHTML = jsinObj;
		}else{
			alert('Error: '+xhr.status);
		}
	}
}

консоль разработчика ругается на 144 строку JSON кода, полученого через GET запрос на список новостей: babruysk.by/ajax_php/news-api.php.(в этой строке только 1 сивол : ]). 

Вот ошибка из консоли: 

Uncaught SyntaxError: Unexpected token ]message: "Unexpected token ]". 

подскажи что делать.

**Comment by Roma36** [comment]
Нашел ошибку. В стринге, которая возвращает json с сервака нужно удалить последнюю запятую.Или подождать, пока Миша пофиксит.

**Comment by EvgenPastushek** [comment]
это я давно сделал. до того пока я ее не убрал, у меня вообще ничего не работало. Сейчас работает, но появляется ошибка при переводе строки в объект

**Comment by Roma36** [comment]
ну хз тогда, странно, у меня работает.

**Comment by EvgenPastushek** [comment]
у тебя все нормально преобразовывается в объект и выводится на страницу?

**Comment by Roma36** [comment]
да

**Comment by Roma36** [comment]
я удаляю вручную последнюю запятую перед ] и все ок. потом просто делаю JSON.parse()
